version: "3"
services: 
    angularapp:
        build:
            context: .
            dockerfile: Dockerfile.Dev
        ports: 
            - "4200:4200"
        volumes: 
            - /app/node_modules
            - .:/app